In [1]:
# Dependencies
from config import homeDepot_API
from serpapi import GoogleSearch
import pandas as pd
import numpy as np
from datetime import datetime
from openpyxl import load_workbook
import os
os.getcwd()

'C:\\Users\\kijah\\Documents\\Data_Bootcamp\\Estimator_Project\\Resources'

STEP 1: EXTRACT

In [2]:
# Created Working 'Material Description by grabbing names from Home Depot'

common_name = []

ids = ['100400409', '100400406', '100137321', '100400405', 
       '202241090', '100144234', '202077145', '202077147', 
       '202288508', '202304774', '202304649', '202304645', 
       '202019377', '202316275', '202019375', '202316276']

for i in ids:

    params = {
      "engine": "home_depot_product",
      "product_id": i,
      "api_key": homeDepot_API
    }

    search = GoogleSearch(params)
    results = search.get_dict()
    products = results['product_results']
    
    common_name.append(products['title'])

https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search

In [3]:
# Order and establish index_name

index_name = []

index_name.append(common_name[3])
index_name.append(common_name[1])
index_name.append(common_name[0])
index_name.append(common_name[5])
index_name.append(common_name[8])
index_name.append(common_name[4])
index_name.append(common_name[2])
index_name.append(common_name[6])
index_name.append(common_name[7])
index_name.append(common_name[12])
index_name.append(common_name[13])
index_name.append(common_name[14])
index_name.append(common_name[15])
index_name.append(common_name[9])
index_name.append(common_name[10])
index_name.append(common_name[11])

#index_name

In [4]:
def searcher(Q, R):
    params = {
      "engine": "google",
      "q": Q,
      "api_key": homeDepot_API
    }
    search = GoogleSearch(params)
    results = search.get_dict()
    products = results["organic_results"]
   
    for p in products[0:10]:
        try:

            title = p['title']
            link = p['link']
            price = (p['rich_snippet']['top']['detected_extensions']['price'])            
    
            result = {'Manufactures Description': title, 'Link': link, 'Material Price': price, 'VENDOR': link}
            R.append(result)
                        
        except (KeyError):
            price = 'NaN'
            result = {'Manufactures Description': title, 'Link': link, 'Material Price': price, 'VENDOR': link}
            R.append(result)

STEP 2: TRANSFORM

In [5]:
# Grab raw data

R = []
for i in range(16):
    R_i = []
   
    searcher(index_name[i], R_i)
    R.append(R_i)

https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search

In [6]:
# Create a data frame
all_prices = []
lowest_prices = []
for i in range(len(R)):
    df = pd.DataFrame(R[i]).assign(Common_name=index_name[i])
# Create a 'Vendor location' column    
    df['Vendor'] = (np.where(df['VENDOR'].str.contains('.'), df['VENDOR'].str.split('.').str[1], df['VENDOR']))
    df.drop(columns =['VENDOR'], inplace = True)
# Change data type of price to numeric and drop NaN's    
    df['Material Price'] = df['Material Price'].apply(pd.to_numeric, args=('coerce',))
    df.dropna(inplace=True)
# Filter out scaling issues
    if i == 0:
        df.drop(df[df['Material Price'] < .77].index, inplace = True)
    if i == 1 or i == 2:
        df.drop(df[df['Material Price'] > 130].index, inplace = True)
        df.drop(df[df['Material Price'] < 2.60].index, inplace = True)
    if i == 4:
        df.drop(df[df['Material Price'] > 130].index, inplace = True)
    if i == 5 or i == 8:
        df.drop(df[df['Material Price'] > 5.98].index, inplace = True)
    if i == 9:
        df.drop(df[df['Material Price'] < 75].index, inplace = True)
    if i == 11 or i == 12:
        df.drop(df[df['Material Price'] < 130].index, inplace = True)
    if i == 13:
        df.drop(df[df['Material Price'] < 500].index, inplace = True)
    if i == 14 or i == 15:
        df.drop(df[df['Material Price'] < 2.60].index, inplace = True)
    df.drop(columns =['Manufactures Description'], inplace = True)
    df['Material Description'] = df['Common_name']
    df.drop(columns =['Common_name'], inplace = True)
    df = df.iloc[:,[3,1,2,0]]
    
    df["Formatted Datetime"] = datetime.now().strftime("%m/%d/%Y %H:%M:%S")
    
    lowest_prices.append(df.min())
    all_prices.append(df)
clean_df = pd.concat(all_prices, axis=0, ignore_index=True)
working_df = pd.DataFrame(lowest_prices)

In [7]:
clean_df.head()

,Material Description,Material Price,Vendor,Link,Formatted Datetime
0,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,7.22,homedepot,https://www.homedepot.com/p/1-2-in-x-10-ft-Ele...,11/05/2022 09:23:07
1,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.99,lowes,https://www.lowes.com/pd/Common-1-2-in-Actual-...,11/05/2022 09:23:07
2,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,4.86,gordonelectricsupply,https://www.gordonelectricsupply.com/p/Allied-...,11/05/2022 09:23:07
3,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.88,supplyworks,https://www.supplyworks.com/Sku/2487615/12-in-...,11/05/2022 09:23:07
4,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.88,ebarnett,https://www.ebarnett.com/Sku/2487615/12-in-x-1...,11/05/2022 09:23:07

In [8]:
headquarter = clean_df.iloc[:,[2]]
locations = headquarter["Vendor"]

headquarters = []

for location in locations:
    params = {
      "q": f"where is {location} headquarters address",
      "location": "United States",
      "hl": "en",
      "gl": "us",
      "api_key": homeDepot_API
    }
    search = GoogleSearch(params)
    results = search.get_dict()
    location_results = results["organic_results"]
    headquarters.append(location_results[1]['snippet_highlighted_words'])

https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search
https://serpapi.com/search

In [9]:
Location_Table = clean_df.iloc[:,[2]]
Location_Table = Location_Table.assign(location=headquarters).drop_duplicates('Vendor').reset_index(drop=True)

Location_Table.head()

                 Vendor                                       location
0             homedepot       [2455 Paces Ferry Rd. Atlanta, GA 30339]
1                 lowes      [1000 Lowes Blvd., Mooresville, NC 28117]
2  gordonelectricsupply  [1290 North Hobbie Street Kankakee, IL 60901]
3           supplyworks    [101 Industrial Dr Bristol, TN, 37620-5422]
4              ebarnett                                     [location]

In [10]:
clean_df.head()

,Material Description,Material Price,Vendor,Link,Formatted Datetime
0,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,7.22,homedepot,https://www.homedepot.com/p/1-2-in-x-10-ft-Ele...,11/05/2022 09:23:07
1,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.99,lowes,https://www.lowes.com/pd/Common-1-2-in-Actual-...,11/05/2022 09:23:07
2,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,4.86,gordonelectricsupply,https://www.gordonelectricsupply.com/p/Allied-...,11/05/2022 09:23:07
3,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.88,supplyworks,https://www.supplyworks.com/Sku/2487615/12-in-...,11/05/2022 09:23:07
4,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,5.88,ebarnett,https://www.ebarnett.com/Sku/2487615/12-in-x-1...,11/05/2022 09:23:07

In [11]:
working_df.head()

,Material Description,Material Price,Vendor,Link,Formatted Datetime
0,1/2 in. x 10 ft. Electric Metallic Tube (EMT) ...,4.86,ebarnett,https://www.ebarnett.com/Sku/2487615/12-in-x-1...,11/05/2022 09:23:07
1,3/4 in. x 10 ft. Electric Metallic Tube (EMT) ...,8.60,amazon,https://www.amazon.com/EMT-Conduit-10-ft-Steel...,11/05/2022 09:23:08
2,1 in. x 10 ft. Electric Metallic Tube (EMT) Co...,17.55,homedepot,https://www.homedepot.com/p/1-in-x-10-ft-Elect...,11/05/2022 09:23:08
3,1/2 in. Electric Metallic Tube (EMT) Set-Screw...,2.29,amazon,https://www.amazon.com/Halex-26270-STEEL-CONNE...,11/05/2022 09:23:08
4,3/4 in. Standard Fitting Electric Metallic Tub...,2.98,homedepot,https://www.homedepot.com/p/Halex-3-4-in-Stand...,11/05/2022 09:23:08

STEP 3: LOAD

In [13]:
# Send a CSV and Excell copies to my computer

xlFile = "C:\\Users\\kijah\\Documents\\Data_Bootcamp\\Estimator_Project\\Consolidated_Estimator_Worksheet.xlsx"

book = load_workbook(xlFile)
writer = pd.ExcelWriter(xlFile, engine = 'openpyxl')
writer.book = book

working_df.to_excel(writer, sheet_name='Working_Table15')
clean_df.to_excel(writer, sheet_name='Clean_Table15')
Location_Table.to_excel(writer, sheet_name='Location_Table2')
writer.save()
writer.close()
    
clean_csv = "C:\\Users\\kijah\\Documents\\Data_Bootcamp\\Estimator_Project\\OldDataFrames\\clean_df17.csv"
clean_df.to_csv(clean_csv, index=False)

working_csv = "C:\\Users\\kijah\\Documents\\Data_Bootcamp\\Estimator_Project\\OldDataFrames\\working_df17.csv"
working_df.to_csv(working_csv, index=False)